# Generated by Django 4.1.5 on 2023-01-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_answer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcomment',
            options={'ordering': ['question', '-post_time'], 'verbose_name': 'FAQ Comment'},
        ),
    ]
