# Generated by Django 4.1.5 on 2023-01-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('thumbnail', models.ImageField(upload_to='reviewcenters/')),
                ('description', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
