# Generated by Django 4.1.5 on 2023-01-29 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AddField(
            model_name='course',
            name='nc_level',
            field=models.PositiveIntegerField(choices=[(1, 'NC1'), (2, 'NC2'), (3, 'NC3'), (4, 'NC4')], default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='review_center',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.reviewcenter'),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='review_center',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.reviewcenter'),
        ),
        migrations.AddField(
            model_name='payment',
            name='review_center',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.reviewcenter'),
        ),
        migrations.AddField(
            model_name='reviewcourse',
            name='review_center',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.reviewcenter'),
        ),
        migrations.AddField(
            model_name='reviewmaterial',
            name='review_center',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.reviewcenter'),
        ),
        migrations.AddField(
            model_name='video',
            name='review_center',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.reviewcenter'),
        ),
    ]
