# Generated by Django 4.1.5 on 2023-01-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_reviewcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcenter',
            name='slug',
            field=models.SlugField(default='', max_length=300, unique=True),
        ),
    ]
