# Generated by Django 4.1.5 on 2023-01-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_reviewcenter_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcenter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
