# Generated by Django 4.1.5 on 2023-01-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_reviewcenter_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcenter',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
