# Generated by Django 4.1.5 on 2023-01-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_course_thumbnail_courseprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Course'),
        ),
    ]
