# Generated by Django 4.1.5 on 2023-01-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_course_options_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='abbreviation',
            field=models.CharField(default='', max_length=16),
        ),
    ]
