# Generated by Django 4.1.5 on 2023-01-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_course_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Category'),
        ),
    ]
