# Generated by Django 4.1.5 on 2023-01-19 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseprice',
            name='previous_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
