# Generated by Django 4.1.5 on 2023-01-19 10:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0014_video_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoComments',
            new_name='VideoComment',
        ),
    ]
