# Generated by Django 4.1.5 on 2023-01-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_rename_videocomments_videocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/media/img/default_video_thumbnail.jpg', upload_to='video_thumbnails/'),
        ),
    ]
