# Generated by Django 4.1.5 on 2023-01-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='/media/img/default_video_thumbnail.png', upload_to='video_thumbnails/'),
        ),
    ]
