# Generated by Django 4.1.5 on 2023-01-19 11:37

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_alter_video_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='date_uploaded',
            new_name='date_posted',
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='img/default_video_thumbnail.png', upload_to='video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
