# Generated by Django 4.1.5 on 2023-01-19 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_rename_date_uploaded_video_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.video'),
        ),
    ]
