# Generated by Django 4.1.5 on 2023-01-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_alter_videocomment_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
