# Generated by Django 4.1.5 on 2023-01-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_alter_videocomment_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
