# Generated by Django 4.1.5 on 2023-01-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_remove_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
