# Generated by Django 4.1.5 on 2023-01-23 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.course')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('content', models.CharField(blank=True, default='', max_length=1024)),
                ('image', models.ImageField(upload_to='review_materials/')),
                ('review_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.reviewcourse')),
            ],
        ),
    ]
