# Generated by Django 4.1.5 on 2023-01-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_reviewcourse_reviewmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcourse',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
    ]
