# Generated by Django 4.1.5 on 2023-01-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_alter_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
