# Generated by Django 4.1.5 on 2023-01-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_alter_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Category'),
        ),
    ]
