# Generated by Django 4.1.5 on 2023-01-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
    ]
