# Generated by Django 4.1.5 on 2023-01-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20230119_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='url',
            field=models.SlugField(allow_unicode=True, help_text='a user friendly url', max_length=60, verbose_name='user friendly url'),
        ),
    ]
