# Generated by Django 4.1.5 on 2023-01-29 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('quiz', '0001_initial'),
        ('system', '0002_delete_student_remove_course_level_course_nc_level_and_more'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='review_center',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.reviewcenter'),
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.company')),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.course')),
                ('job', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.jobpost')),
                ('quiz', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.quiz')),
                ('review_center', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.reviewcenter')),
                ('review_material', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.reviewmaterial')),
                ('review_video', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.video')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('school', models.CharField(default='', max_length=50)),
                ('date_of_graduation', models.DateField(blank=True, null=True)),
                ('deans_name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('contact_person_number', models.CharField(default='', max_length=11)),
                ('contact_person_name', models.CharField(default='', max_length=50)),
                ('contact_person_relation', models.IntegerField(choices=[(1, 'Father/Mother'), (2, 'Husband/Wife/Partner'), (3, 'Uncle/Aunt'), (4, 'Grandmother/Grandfather'), (5, 'Guardian'), (6, 'Others')], default=1)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
            },
        ),
    ]
