# Generated by Django 4.1.5 on 2023-01-29 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_delete_student_remove_course_level_course_nc_level_and_more'),
        ('authentication', '0002_customuser_review_center_studentprogress_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='review_center',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.reviewcenter'),
        ),
    ]
