# Generated by Django 4.1.5 on 2023-01-29 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_course_review_center'),
        ('authentication', '0003_alter_customuser_review_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentReviewCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_center', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.reviewcenter')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
