# Generated by Django 4.1.5 on 2023-01-29 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_payment_student'),
        ('authentication', '0004_currentreviewcenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprogress',
            name='review_material',
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='review_course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.reviewcourse'),
        ),
    ]
