# Generated by Django 4.1.5 on 2023-01-29 04:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('overview', models.CharField(default='', max_length=1000)),
                ('company_size', models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('average_processing_time', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('benefits_and_others', models.CharField(default='', max_length=256)),
                ('thumbnail', models.ImageField(blank=True, default='', upload_to='company_thumbnails/')),
                ('logo', models.ImageField(blank=True, default='', upload_to='company_logos/')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Company Industries',
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
                ('job_description', models.CharField(default='', max_length=256)),
                ('job_requirements', models.CharField(default='', max_length=259)),
                ('job_type', models.PositiveSmallIntegerField(choices=[(1, 'Full Time'), (2, 'Part Time')], default=1)),
                ('career_level', models.CharField(default='', max_length=60)),
                ('years_of_experience', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('address', models.CharField(default='', max_length=100)),
                ('salary_range', models.CharField(blank=True, default='', max_length=50)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(allow_unicode=True, default='', unique=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.companyindustry'),
        ),
    ]
