# Generated by Django 4.1.5 on 2023-01-20 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='career_level',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
