# Generated by Django 4.1.5 on 2023-01-30 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
