# Generated by Django 4.1.5 on 2023-01-20 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobpost_career_level_jobpost_years_of_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='name',
            new_name='title',
        ),
    ]
