# Generated by Django 4.1.5 on 2023-01-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_certificate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(default='', upload_to='certificate/'),
            preserve_default=False,
        ),
    ]
