# Generated by Django 4.1.5 on 2023-01-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_rename_name_jobpost_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companyindustry',
            options={'verbose_name_plural': 'Company Industries'},
        ),
        migrations.AddField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
