# Generated by Django 4.1.5 on 2023-01-30 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_company_review_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ManyToManyField(to='job.certificate')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobpost')),
            ],
        ),
    ]
