# Generated by Django 4.1.5 on 2023-01-30 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_exam_paper_alter_quiz_random_order'),
        ('job', '0008_jobrequirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequirements',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='jobrequirements',
            name='job_post',
        ),
        migrations.AddField(
            model_name='jobrequirements',
            name='certificate_quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_requirements',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.jobrequirements'),
        ),
    ]
