# Generated by Django 4.1.5 on 2023-01-30 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_remove_jobrequirements_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='job_requirements',
        ),
        migrations.AddField(
            model_name='jobrequirements',
            name='job_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.jobpost'),
        ),
    ]
