# Generated by Django 4.1.5 on 2023-01-30 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_jobapplication_job_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.jobpost'),
        ),
    ]
