# Generated by Django 4.1.5 on 2023-01-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'For interview'), (3, 'For Requirements'), (4, 'Hired')], default=1),
        ),
    ]
